Reload
Nourepide/CryptocurrencyMonitor pull request #18
Opened 2018-11-09 21:34 UTC by Nourepide

2018-11-12 08:05 UTC, olegcherr requested changes

2018-11-12 08:05 UTC, olegcherr commented on app/src/main/java/net/nourepide/learning/cryptocurrencymonitor/MainActivity.kt
> +            viewModel.reload()
Вызов `reload` - это фактически прямое указание Модели что нужно сделать с данными. То есть считай - прямая модификация данных. А это нарушение принципа разделения ответственности, которое может привести к нежелательным трудностям.

Представь, что внутри Модели появляется какое-то новое условие, из-за которого нельзя в данный момент выполнять `reload`. Например в данный момент уже происходит какой-то другой процесс. А мы тут берём, и выполняем `reload` прямо из View. Это фигово.

Поэтому в MVP-подходах делают следующим образом:
View никогда не указывает что именно нужно сделать Модели. View лишь сообщает какое действие совершил пользователь. А затем Модель сама принимает решение как нужно отреагировать на данное действие.

В нашем случае модель должна иметь публичный метод, допустим, `handleRefreshSwipe`. View должна вызывать именно его, сообщая таким образом, что юзер запросил обновление данных. Если это в данный момент возможно, то Модель вызовет свой внутренний приватный метод `reload` и перезагрузит данные.

Такие дела))

2018-11-13 18:38 UTC, olegcherr requested changes

2018-11-13 18:38 UTC, olegcherr commented on app/src/main/java/net/nourepide/learning/cryptocurrencymonitor/MainViewModel.kt
> +        if (!isLoading.value!!) reload()
Теоретически, если этот код вызовется до того, как `isLoading` будет установлен в true или false, то тут будет NPE.

Рекомендую в подобных случаях писать так:
`isLoading.value != true`

И кстати эту проверку вообще можно перенести в самое начало `reload()`. А то он у нас довольно тупой, и легко может вызваться 2 раза подряд, если кто-то его вызовет, не проверив перед этим `isLoading`.

2018-11-13 18:38 UTC, olegcherr commented on app/src/main/java/net/nourepide/learning/cryptocurrencymonitor/MainViewModel.kt
> +    val isLoading = mutableLiveData<Boolean>()
Не понимаю почему бы не установить значение по умолчанию:
`mutableLiveData(false)`

Зачем тебе нужны нуллы?

2018-11-13 18:38 UTC, olegcherr commented on app/src/main/java/net/nourepide/learning/cryptocurrencymonitor/MainViewModel.kt
>              data.postValue(null)
Я бы не обулял переменную. Зачем? Пусть список продолжает показываться.

2018-11-13 18:38 UTC, olegcherr commented on app/src/main/java/net/nourepide/learning/cryptocurrencymonitor/MainViewModel.kt
>              isLoading.postValue(true)
Установку `isLoading=true` я бы вынес из `thread {` наверх, чтобы эта переменная обновлялась как можно раньше.
Иначе может быть ситуация, что `reload()` будет вызван 2 раза подряд, т.к. флаг `isLoading` обновляется лишь спустя какое-то время, в фоновом потоке.

2018-11-13 18:41 UTC, Nourepide commented on app/src/main/java/net/nourepide/learning/cryptocurrencymonitor/MainViewModel.kt
>              data.postValue(null)
Я уже собирался так сделать, но решил оставить что-бы была уверенность в обновлении, теперь когда это доказанно это можно и убрать

2018-11-13 19:37 UTC, olegcherr commented on app/src/main/java/net/nourepide/learning/cryptocurrencymonitor/MainViewModel.kt
> +        if (isLoading.value == true) return else isLoading.value = true
`else` тут как бы лишний :)

Обычно пишут так:
```
if (isLoading.value == true) return
isLoading.value = true
```

2018-11-13 19:38 UTC, olegcherr approved these changes

2018-11-13 19:46 UTC, Nourepide commented on app/src/main/java/net/nourepide/learning/cryptocurrencymonitor/MainViewModel.kt
> +        if (isLoading.value == true) return else isLoading.value = true
Верно, я изначально так и сделал когда перенёс проверку в reload но решил в рамках эксперемента обьеденить эти две строчки в один логический элемент целью которого является синхронизация. При первом взгляде кажется что уменьшилась читаемость кода но с другой стороны становится понятен контекст `isLoading.value = true` и его предназначение

2018-11-13 19:52 UTC, amal commented on app/src/main/java/net/nourepide/learning/cryptocurrencymonitor/MainViewModel.kt
> +        if (isLoading.value == true) return else isLoading.value = true
Даже вот так скорее, если прям читабельно делать.
Тогда видно как стандартный единый блок.
```kotlin
if (isLoading.value == true)
  return
isLoading.value = true
```

2018-11-13 19:54 UTC, olegcherr commented on app/src/main/java/net/nourepide/learning/cryptocurrencymonitor/MainViewModel.kt
> +        if (isLoading.value == true) return else isLoading.value = true
Ну оставь, если тебе нравится.
Но вообще, смысла в этом нет абсолютно.

2018-11-13 20:00 UTC, olegcherr commented on app/src/main/java/net/nourepide/learning/cryptocurrencymonitor/MainViewModel.kt
> +        if (isLoading.value == true) return else isLoading.value = true
У каждого своё представление о прекрасном. Именно поэтому я ищу способ автоматического форматирования кода. Чтобы не было разногласий, и программист никогда не задумывался о форматировании кода.

2018-11-13 20:01 UTC, olegcherr commented on app/src/main/java/net/nourepide/learning/cryptocurrencymonitor/MainViewModel.kt
> +        if (isLoading.value == true) return else isLoading.value = true
В общем сливай. `else` тут конечно лишний, но он меня не интересует с точки зрения обучения. Так что мне пох))

2018-11-13 20:04 UTC, Nourepide commented on app/src/main/java/net/nourepide/learning/cryptocurrencymonitor/MainViewModel.kt
> +        if (isLoading.value == true) return else isLoading.value = true
Ну я же не нарушаю этим Coding Conventions :+1: 
Просто так исторически сложилось что я не особо люблю установку значений переменной вне логического выражения

2018-11-13 20:07 UTC, merged

2018-11-13 20:19 UTC, olegcherr commented on app/src/main/java/net/nourepide/learning/cryptocurrencymonitor/MainViewModel.kt
> +        if (isLoading.value == true) return else isLoading.value = true
Хз. Я наоборот не вижу смысла соединять действия в один блок, если их можно разделить.
Например, понадобится тебе добавить ещё каких-то проверок между
`if (isLoading.value == true) return`
и
`isLoading.value = true`.
И всё, придётся разлеплять этот код, как ни крути.

Вот абстрактный пример. Подобный код, но с несколькими сложными проверками:

```
if (isLoading) return

val connection = getConnection()
val type = db.requestType()
if (connection.isActive(type)) return

isLoading = true
connection.setActive(type, true)
```

То есть мы тут сначала быстро проверяем `isLoading`, а затем выполняем ресурсоёмкую проверку `connection`. И только после этого устанавливаем флаги в `true`.

Если попробовать этот код написать в твоём стиле, то будет как-то так:
```
val connection = getConnection()
val type = db.requestType()

if (isLoading || connection.isActive(type)) return
else {
  isLoading = true
  connection.setActive(type, true)
}
```
В данном случае мы всегда выполняем ресурсоёмкие операции `getConnection` и `db.requestType`, что нехорошо.

Это абстрактный пример того, в каком направлении обычно разрастается код, и почему нет смысла стараться скреплять код вместе. Код наоборот надо разделять по возможности.

2018-11-13 20:34 UTC, Nourepide commented on app/src/main/java/net/nourepide/learning/cryptocurrencymonitor/MainViewModel.kt
> +        if (isLoading.value == true) return else isLoading.value = true
Массовая установка значений для меня является уже логическим блоком, если будет необохдимость их разделить я обязательно так и сделаю.
В моём случае я уже описал причины по которым я в рамках эксперемента обьеденил две конструкции в один логический (Для понимания) блок.
Я понимаю что вы ставите на первые места понятность кода и его качество, но я считаю что многие разработчики зря не обращают внимание на его красоту (Конечно-же в рамках CC), может показатся что зачастую качественный код уже сам по себе является красивым для человечкского восприятия контекста и его логической нагруженности но на деле это не гарантирует этих качеств. Можете считать моё поведение близкое к урбанизаторскому, так как одна из причин, при этом не единственная, являлось уменьшение кода за пределом `thread {` так как основной код находится в нём, эта причина полностью контекстная и не является приминимой везде, конкретно - такую логику человечского восприятия нельзя с уверенностью сформулировать в правилах, из-за чего и нельзя будет воссоздать в статических анализаторах и форматировщиках, это чисто субьективная оценка.