Dialog
Nourepide/CryptocurrencyMonitor pull request #20
Opened 2018-11-15 19:43 UTC by Nourepide

2018-11-16 05:46 UTC, olegcherr requested changes

2018-11-16 05:46 UTC, olegcherr commented on app/src/main/java/net/nourepide/learning/cryptocurrencymonitor/MainDialogFragment.kt
> +        isCancelable = false
Если ты глянешь исходный код этого поля, то увидишь, что `Cancelable` - это свойство Диалога. Соответственно устанавливать его в `false` можно в методе `onCreateDialog`, через билдер:
`.setCancelable(false)`

И кстати `init` (и `constructor`) вообще не надо использовать в Активити и Фрагментах. Для всего есть методы жизненного цикла. И я сходу не могу придумать ситуацию, когда их будет недостаточно, и понадобится использовать `init`.

2018-11-16 05:46 UTC, olegcherr commented on app/src/main/java/net/nourepide/learning/cryptocurrencymonitor/MainListAdapter.kt
> +        }
Мне кажется зря ты диалог запихнул в Адаптер. Да ещё и прямо в `setOnClickListener`.

Диалог - такая штука, которая всецело зависит от родительского Активити или Фрагмента. Поэтому я бы показывал его оттуда. А то получается, что Адаптер занимается слишком многими вещами. Это не очень хорошо, и ломает по сути [паттерн "Адаптер"](https://ru.wikipedia.org/wiki/%D0%90%D0%B4%D0%B0%D0%BF%D1%82%D0%B5%D1%80_(%D1%88%D0%B0%D0%B1%D0%BB%D0%BE%D0%BD_%D0%BF%D1%80%D0%BE%D0%B5%D0%BA%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F)). Адаптер в идеале должен заниматься преобразованием исходных данных в тот вид, который нужен RecyclerView для построения списка, и всё. Не следует пихать в него всё что только можно (см. каммент выше, касательно Адаптера).

Плюс у тебя сейчас Диалог никак не отражён в состоянии (во ViewModel), и Модель фактически не знает что сейчас делает юзер.

Вощем...
Полагаю, лучше всего сделать следующим образом.
- По клику должно происходить оповещение Модели о том, по какому именно элементу был совершён клик. Навешивать слушатель клика можно прямо в XML. Разумеется нужно будет передавать в Модель в XML.
- Модель должна обновить своё поле, означающее что диалог в данный момент открыт. Можно прям сделать поле типа `val chosenCurrency = mutableLiveData<Cryptocurrency>()`. Если оно установлено, то значит диалог открыт.
- Активити должна слушать это поле, и открывать диалог, когда это поле установлено.

2018-11-16 05:46 UTC, olegcherr commented on app/src/main/java/net/nourepide/learning/cryptocurrencymonitor/MainListAdapter.kt
>          viewModel.data.observe(lifecycle, Observer { notifyDataSetChanged() })
Мне таки не нравится что адаптер сам навешивает слушателя на нужное ему поле в Модели, и сам когда надо обновляет данные. Это не очень хороший подход. 1) Во-первых, тебе из-за этого приходится передавать в Адаптер много лишних вещей: `LifecycleOwner` и `MainViewModel`. 2) А во-вторых, хорошо когда Адаптер переиспользуемый. То есть чтобы можно было заюзать этот же Адаптер, но с другими данными. Потому что часто бывает, что Адаптер используется для нескольких разных списков. Глянь например [вот тут](https://github.com/Anizoptera/Android-Architecture-Best-Practices/blob/3965c0d858327f1e890bcecb4ad3b0412240390a/app/src/main/java/azadev/android/architecture/feat/part4/Part4Activity.kt). Там 2 RecyclerView использующих один и тот же Адаптер, но каждый из них имеет свои данные. Это удобно и правильно.

2018-11-16 18:20 UTC, Nourepide commented on app/src/main/java/net/nourepide/learning/cryptocurrencymonitor/MainDialogFragment.kt
> +        isCancelable = false
В `onCreateDialog` у нас создаётся не DialogFragment а AlertDialog, достаточно попробывать 
```
override fun onCreateDialog(savedInstanceState: Bundle?) = AlertDialog.Builder(context!!)
        .setTitle(arguments!!["TITLE"] as String)
        .setPositiveButton("Close", null)
        .setCancelable(false)
        .show()!!
```
что-бы убедиться в том что новое диалоговое окно будет закрыватся при любом случайном нажатии.

Насчёт конструктора я уже прочёл, а вот насчёт init так ничего и не нашёл (Хотя я специально искал), все параметры успешно хранятся в фрагменте который я специально использовал как обёртку для сохранения диалога в лайфциклах.
Я конечно могу сделать вот так
```
override fun onCreateDialog(savedInstanceState: Bundle?) = AlertDialog.Builder(context!!)
        .setTitle(arguments!!["TITLE"] as String)
        .setPositiveButton("Close", null)
        .show()!!
        .also { isCancelable = false }
```
что-бы этот параметр устанавливался при каждом пересоздании диалога, но как-то не вижу в этом смысла если фрагмент по итогу у нас выживает всегда в отличии от диалога, для проверки можно даже сделать
```
.also {
    when (isCancelable) {
        true -> {
            Log.d("onCreateDialog", "isCancelable equals true")
            isCancelable = false
        }

        false -> {
            Log.d("onCreateDialog", "isCancelable already false")
        }
    }
}
```
и увидеть что `true` срабатывает один единственный раз при создании фрагмента, и после при каждом пересоздании диалога у нас он будет `false`.
Сообственно мне кажется что устанавливать переменную класса которая будет использованна в промежутке между его созданием и смертью (!= пересозданием) в блоке инициализации нормальная практика. Да и сообственно говоря передача аргументов в конструкторе запрещена так как она необходима действительно обьектам подверженным лайфциклу, например диалогу, там это оправданно. Но вот задавать свойства не подверженому (в моих условиях) лайфциклу как подверженому, дополнительная неоправданная трата ресурсов. На таком-же уровне я могу воссоздавать данные при перезапуске приложения, лайфциклично? Да. Нужно? Не уверен.
Ну если тебе принципиально, можно сделать вот так
```
MainDialogFragment()
    .setArguments("TITLE", viewHolder.binding.cryptocurrency!!.run { "$name : $symbol" })
    .apply { isCancelable = false }
    .show((lifecycle as AppCompatActivity).supportFragmentManager, "tag")
```
но разницы с точки зрения работы кода нет вообще никакой.

2018-11-16 19:43 UTC, olegcherr commented on app/src/main/java/net/nourepide/learning/cryptocurrencymonitor/MainDialogFragment.kt
> +        isCancelable = false
Чувак, ну это просто хреновая практика - делать что-то в конструкторах Фрагментов и Активити. Она часто приводит к непонятным багам, связанным с пересозданием Активити/Фрагментов. Поэтому рекомендую стараться всё что нужно прописывать в подходящих методах жизненного цикла.

> задавать свойства не подверженому (в моих условиях) лайфциклу как подверженому, дополнительная неоправданная трата ресурсов

Никаких ресурсов тут не тратится. Ты вообще о чём?

Кстати, только что заметил что ты в ` onCreateDialog` сразу вызываешь `.show()`. А там нужно вызывать `.create()`. Фрагмент дальше сам решит когда делать show.

В общем на твоём месте я бы убрал конструктор и написал вот так:

```
    override fun onCreateDialog(savedInstanceState: Bundle?): AlertDialog {
        isCancelable = false

        return AlertDialog.Builder(context!!)
            .setTitle(arguments!!["TITLE"] as String)
            .setPositiveButton("Close", null)
            .create()
    }
```

2018-11-16 20:25 UTC, Nourepide commented on app/src/main/java/net/nourepide/learning/cryptocurrencymonitor/MainDialogFragment.kt
> +        isCancelable = false
Считать конструктор Java и блок инициализации Kotlin одинаковым каокй-то карго-культ
> связанным с пересозданием Активити/Фрагментов

Мне кажется я нормально описал почему мой фрагмент не пересоздаётся и не должен пересоздаватся, пересоздаётся у нас диалог и вот он уже подвержен лайфциклу для которого и стоит запрет на использования [конструктора](http://kotlinlang.org/docs/reference/classes.html#constructors)

> Никаких ресурсов тут не тратится. Ты вообще о чём?

Человеческие ресурсы, они отвечают за продуктивность и впоследствии влияют на все параметры написания кода

Насчёт show не знал, но теперь всё встало на места.

```
override fun onCreateDialog(savedInstanceState: Bundle?): AlertDialog {
        isCancelable = false
```
Зачем нам указывать параметры фрагмента при каждом пересоздании диалога? Я же выше показал что это полностью бесполезная операция которая срабатывает лишь один раз при инициализации фрагмента который уже потом вызывает создание диалога.

Например если я вообще уберу `show` при создании `MainDialogFragment()` то эта функция у нас даже не сработает. Получается что диалог у нас вмешивается в работу фрагмента и это нарушает прицнипы инкапсуляции.  А если скажем мне понадобится этот-же фрагмент но с какой-то другой логикой но при этом `isCancelable` у него должен быть `false`, то мне придётся специально ради этого вызывать `show`?

Вот тут и кроется моё непонимание, ради того что-бы не использовать подходящее место для инициализации параметра (который в отличии от конструктора не запрещён), для фрагмента который не подвержен внешнему воздействию пересоздания активити, приходится нарушать уже основные правила ООП. Оно действительно стоит того эффекта плацебо защишённости?

Я конечно могу вынести установку параметра фрагмента из блока `init`, но точно не в место инициализации диалога

2018-11-16 21:06 UTC, olegcherr commented on app/src/main/java/net/nourepide/learning/cryptocurrencymonitor/MainDialogFragment.kt
> +        isCancelable = false
Не вижу смысла продолжать тратить время на эту мелочь. У тебя есть вся информация чтобы принять решение, которое тебя устроит.

2018-11-16 21:19 UTC, amal commented on app/src/main/java/net/nourepide/learning/cryptocurrencymonitor/MainDialogFragment.kt
> +        isCancelable = false
> Считать конструктор Java и блок инициализации Kotlin одинаковым каокй-то карго-культ

@Nourepide Конструктор Java и блок инициализации Kotlin - это одно и тоже.
Разница не принципиальна - чисто синтаксическая & мелкие нюансы реализации.
Блок инициализации - сахар для дефолтного конструктора.

> мой фрагмент не пересоздаётся и не должен пересоздаватся, пересоздаётся у нас диалог и вот он уже подвержен лайфциклу

Абсолютно все компоненты андроида подвержены лайфциклу, даже не представляешь на сколько. Только получая логи ошибок с тысяч разных устройств становится понятно что там может твориться примерно что угодно.

Поэтому в компонентах андроида принято простое правило - не писать логику в конструкторах. Просто не стоит так делать.

Обычные классы в андроиде тоже зависят от лайфцикла, конечно. Но их андроид просто прибьёт целиком не разбираясь, так что в них можно юзать конструктор естественно.

2018-11-16 21:58 UTC, Nourepide commented on app/src/main/java/net/nourepide/learning/cryptocurrencymonitor/MainDialogFragment.kt
> +        isCancelable = false
Действительно, конструктор Java == init Kotlin, и конструктор Java == constructors Kotlin
Получается init == contructors в Kotlin?

При создании конструктора IDEA высветит что __передача параметров__ в Fragments это плохо так как для самого фрагмента она не нужна а следовательно нужна для чего-то иного что подверженно лайфциклу, а для это-го есть лайфцикло-безопасный arguments.

Но допустим где мне установить стартовые параметры фрагмента? За столь большую пелену текста еще не было указанно подходящие место для это-го, вот прямо что-бы как setOnClassload {  }  для JVM который является блок init Kotlin, я собственно и не против его перенести, просто для это-го нужно показать пример почему в данном случае это плохо, а то получается что это плохо потому что в Java конструктор с передачей параметров отвечал еще и за инициализацию, сообственно сейчас для меня выглядит как эксперимент с обезьянами и душем. Это плохо, а куда перенести не ясно.

Вот например я сейчас коммит отправил с удалением богопротивного блока init, нас устраивает? А что изменилось для JVM?

> Абсолютно все компоненты андроида подвержены лайфциклу

Видимо ViewModel [у нас исключение](https://github.com/Nourepide/CryptocurrencyMonitor/pull/16#discussion_r230874773). И onCreate в Activity у нас не оказывает влияние на DialogFragment, неужели это не лайфцикл? Именно это я называю не подверженный влиянию лайфциклу, тоесть я понимаю что по итогу он влиянию всё таки подвержен, например засыпанию приложения или его закрытию, но они не находятся на уровне прямого взаимодействия с фрагментов, тоесть ему от них ни тепло не холотно, не надо-же мне делать восстоновление диалога при запуске приложения (Этот-же пример я кстати привёл выше, именно с этим же мотивом)

А знаете, в процессе разбора данного вопроса, я пришёл к интересному выводу. Блок инициализации в модели лайфцикла у нас является onCreate. Но слишком многословно, вместе с блоком super который по сути здесь и не используется.

2018-11-17 05:03 UTC, olegcherr commented on app/src/main/java/net/nourepide/learning/cryptocurrencymonitor/MainDialogFragment.kt
> +        isCancelable = false
> Блок инициализации в модели лайфцикла у нас является onCreate.

Да, всё верно.

> Но слишком многословно, вместе с блоком super который по сути здесь и не используется.

Тоже верно. Создавать `onCreate` чисто ради `isCancelable = false` - это довольно многословно. Поэтому я и [предложил](https://github.com/Nourepide/CryptocurrencyMonitor/pull/20#discussion_r234326374) не париться, и запихнуть всё в `onCreateDialog`. Благо `isCancelable = false` - операция нересурсоёмкая, и можно пихать её куда угодно, заботясь лишь о читаемости кода. Но в идеале да, надо положить её в `onCreate`.

И кстати `onCreate` - это не так многословно, как то что ты сделал сейчас 😃 
`fun setCancelableDialog(value: Boolean): MainDialogFragment`
Да ещё и вызывать этот метод приходится при создании фрагмента))

***

В общем, в итоге считаю эту дискуссию полезной, т.к. ты кажется много чего полезного для себя открыл. Это хорошо.

2018-11-17 06:03 UTC, amal commented on app/src/main/java/net/nourepide/learning/cryptocurrencymonitor/MainDialogFragment.kt
> +        isCancelable = false
> Видимо ViewModel [у нас исключение](https://github.com/Nourepide/CryptocurrencyMonitor/pull/16#discussion_r230874773).

Не исключение. Просто это для андроида `ViewModel` -- обычный класс, о котором он ничего не знает :)
Андроид уведомляет о лайфцикле только ограниченное число классов. Активити, Фрагменты, Сервисы, и т.п. - самое основное. С ними андроид может работать более гибко. Остальные могут быть косвенно уведомлены если это сделает какой-то компонент. Но вообще андроид прибьёт их не задумываясь об этом )

2018-11-24 07:09 UTC, olegcherr requested changes

2018-11-24 07:09 UTC, olegcherr commented on app/src/main/java/net/nourepide/learning/cryptocurrencymonitor/MainActivity.kt
> +            viewModel.data.observe(this@MainActivity, Observer { adapter!!.notifyDataSetChanged() })
Мне кажется ты перебарщиваешь с хелпером `apply{}`. Слишком много туда напихал. Код уже начал гораздо хуже читаться. Плюс эти `@MainActivity`...

Ладно ещё когда там была просто небольшая настройка `recyclerView`. А теперь там уже даже слушатели навешиваются. В общем уже слишком много важного кода скрывается за скобками внутри лямбды :) 

И ещё мне не нравится приведение к non-null - `adapter!!`. Зачем делать лишние действия, когда можно просто сохранить адаптер в переменную? К тому же это будет более надёжно. А то вдруг на момент приведения к non-null поле `adapter` уже кто-то обнулил :) Да, это невозможно в recyclerView, но всё равно это good practice.

В общем рекомендую переписать этот грязный код вот так:
```
        val adapter = MainListAdapter(viewModel)
        binding.recyclerView.layoutManager = LinearLayoutManager(this)
        binding.recyclerView.adapter = adapter

        viewModel.data.observe(this, Observer {
            adapter.notifyDataSetChanged()
        })
```

2018-11-24 07:09 UTC, olegcherr commented on app/src/main/java/net/nourepide/learning/cryptocurrencymonitor/MainActivity.kt
> +                viewModel.clearCryptocurrency()
А какой смысл обнулять `chosenCryptocurrency` при открытии диалога? У тебя же получается несоответствие данных и представления. `chosenCryptocurrency` = `null`, а диалог открыт. Получается что View неверно отражает данные Модели.

Обнулять `chosenCryptocurrency` тебе нужно при **_закрытии_** диалога.

Тут есть 2 варианта:

1. Самый простой - слушать OnDismiss, и после закрытия обнулять `chosenCryptocurrency`. Тут получается, что модель никак не может повлиять на закрытие диалога. Она лишь обрабатывают закрытие постфактум. А если по какой-то причине сейчас нельзя было закрывать диалог? Такое без проблем может быть в случае более сложных, интерактивных диалогов.

2. Правильный - слушать клик по кнопке `Close`, затем вызывать у модели метод типа `handleDialogCloseRequest`, и модель уже будет решать: закрыть диалог или нет. Если закрыть, то она сама обнуляет `chosenCryptocurrency`. Информация об этом приходит сюда, в наш слушатель. И тут мы вызываем `dismiss()` у диалога. Диалог закрыт :) Таким образом у нас будет соблюдаться важный принцип однонаправленного потока данных - unidirectional data-flow.

Решай сам какой вариант выбрать. Можно и первый, пофиг. Главное пойми и проникнись вторым вариантом. Он очень важен.

2018-11-24 07:09 UTC, olegcherr commented on app/src/main/java/net/nourepide/learning/cryptocurrencymonitor/MainViewModel.kt
> +    val chosenCryptocurrency = mutableLiveData<Cryptocurrency>()
Как думаешь, может в случае, когда значение действительно может быть null, указывать нуллабл тип?
То есть вот так вот:
`mutableLiveData<Cryptocurrency?>()`

Разницы во внешнем коде никакой. Но как-то более понятно становится, что значение действительно может быть null, и не рекомендуется использовать `!!`.

2018-11-25 05:58 UTC, olegcherr requested changes

2018-11-25 05:58 UTC, olegcherr commented on app/src/main/java/net/nourepide/learning/cryptocurrencymonitor/MainActivity.kt
> +    private val adapter by lazy { MainListAdapter(viewModel) }
Зачем нужен этот делегат, когда можно просто обойтись переменной в `onCreate`?
`by` знаешь как работает? Создаётся целый класс. А `lazy` ещё и синхронизацию содержит.
В данном случае это не слишком критично, но вообще ты тут разбазариваешь ресурсы конкретно))

2018-11-25 05:58 UTC, olegcherr commented on app/src/main/java/net/nourepide/learning/cryptocurrencymonitor/MainDialogFragment.kt
> +        .setOnClickPositive { close(viewModel.clearCryptocurrency()) }
2 проблемы:

1. Во-первых нельзя явно говорить Модели что нужно сделать. Нельзя просить её очистить Cryptocurrency.
Можно лишь сообщать Модели, что юзер нажал на копку, и всё. Дальше мы ничего не знаем что захочет делать модель.
То есть во-первых нужно переименовать метод в `handleCloseClick`.
Никак чёт у тебя не закрепится подход "Passive View".

2. Во-вторых, у тебя тут всё же получается императивность, а не реактивность.
Представь, что в какой-то момент Модель решит закрыть диалог сама. По истечению какого-то времени например, или ещё как-то. Чтобы это сделать, она обнулит `chosenCryptocurrency`.
Но диалог у тебя останется открыт. Получится несоответствие данных и представления.
Поэтому открывать и закрывать диалог тебе нужно лишь слушая изменения `chosenCryptocurrency`, и всё. Не нужно делать императивное закрытие по какому-то условию.
У тебя же тут фактически получается такая вот логика:
`if (viewModel.clearCryptocurrency()) dismiss()`
Логика не должна быть во View. Чем меньше кода во View, тем лучше.

2018-11-27 15:29 UTC, Nourepide commented on app/src/main/java/net/nourepide/learning/cryptocurrencymonitor/MainActivity.kt
> +    private val adapter by lazy { MainListAdapter(viewModel) }
Я не против убрать но у этого подхода кроме минусов траты незначительных ресурсов есть так-же и плюсы.
* Если просто убрать делегат то при загрузке класса произойдет начальная инициализация которая кинет исключение так как она происходит до загрузки базовых комппонентов Android
* Если перенести её в метод то будет нельзя вызывать её из всего класса (`this`) 
* Она потеряет логическое имя после переименовывания так как нельзя присвоить `binding.recyclerView.adapter = adapter` без указания уточнающего `this` 

Так-же я провёл замеры и нашёл интересную закономерность.
С делегатовой переменной потребление RAM на устройстве приложением являеться 29.6  Mb, с обычной же внутри функции - 29.7, я провёл 3 замера каждого типа чередую их между собой. Вероятнее всего Kotlin код очень хитро оптимизирован и всё это подчищается после срабатывания.

В общем я не отрицаию что делегаты могут быть менее производительными чем обычная инициализация в функции, но предлагаю оставить всё как есть, все равно не критично.

2018-11-27 16:07 UTC, olegcherr requested changes

2018-11-27 16:07 UTC, olegcherr commented on app/src/main/java/net/nourepide/learning/cryptocurrencymonitor/MainDialogFragment.kt
> +        })
Смари какая фигня получилась:

Ты открываешь диалог из Активити, слушая `chosenCryptocurrency`. А закрывается диалог сам, когда посчитает нужным. В данном случае он тоже слушает `chosenCryptocurrency`, и видимых проблем как бы нет.  Но компонент получается не полностью контролируемым со стороны того, кто его использует.

Это я описал архитектурную проблему.

Ну а чисто если практически, то зачем добавлять 2 обсервера в двух разных местах, когда можно всё сделать в одном месте, и сразу будет видна вся логика открытия и закрытия диалога?

2018-11-27 16:12 UTC, olegcherr commented on app/src/main/java/net/nourepide/learning/cryptocurrencymonitor/MainActivity.kt
> +    private val adapter by lazy { MainListAdapter(viewModel) }
> Если просто убрать делегат

Нене. Адаптер надо создавать в `onCreate` и всё.

> Если перенести её в метод то будет нельзя вызывать её из всего класса (this)

А тебе это нужно? У нас весь активити - это один метод `onCreate` и всё))

> Она потеряет логическое имя после переименовывания так как нельзя присвоить binding.recyclerView.adapter = adapter без указания уточнающего this

Ммм... чо?

Вот всё что тебе надо:

```
        val adapter = MainListAdapter(viewModel)
        binding.recyclerView.layoutManager = LinearLayoutManager(this)
        binding.recyclerView.adapter = adapter
```

2018-11-27 16:14 UTC, olegcherr commented on app/src/main/java/net/nourepide/learning/cryptocurrencymonitor/MainActivity.kt
> +    private val adapter by lazy { MainListAdapter(viewModel) }
> Если перенести её в метод то будет нельзя вызывать её из всего класса (this)

Вот об этом вообще не думай. Не надо создавать бесполезные поля класса, когда можно обойтись локальной переменной.

2018-11-27 18:52 UTC, olegcherr approved these changes

2018-11-27 18:58 UTC, merged